services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    image: ${APP_NAME}:${APP_TAG}
    container_name: app
    restart: unless-stopped
    ports:
      - '${FRONTEND_PORT}:3000'
      - '${BACKEND_PORT}:3200'
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - network
    depends_on:
      - postgres

  postgres:
    image: postgres:${POSTGRES_TAG}
    container_name: postgres
    restart: unless-stopped
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    name: network
    driver: bridge